### ISSUE TITLE
Solus Linux package

### ISSUE THREAD

**Issue by rajkrish** [notable/notable#652]
I did not find any easy to use build/install instructions.  Since I am on Solus Linux, the available RPM/Deb/Snap packages are useless to me.

I don't have any idea about NPM and Electron package installation or deployment.  I checked that I have `/usr/bin/npm` installed.  I also managed to install Electron with `npm install electron -g` on the host.  However I failed to install and/or run Notable with Electron.  

### Feature description
Please provide NPM based Electron and Notable installation instructions on the README page, or provide additional links where we could learn how to install those.

Clear installation documentation for the NPM / Electron uninitiated.
### Feature motivation

No easy to install/configure documentation exists on how to install Notable on Linux distros that DO NOT support the provided RPM/Deb/Snap packages.

**Comment by fabiospampinato** [comment]
There's no need to fiddle with npm or Electron, all the published formats are available [here](https://github.com/notable/notable/releases). If none of those is usable in Solus Linux then I'm afraid you can't install it.

What format are apps for Solus packaged in? Perpahs we could support that one as well in the future.

**Comment by Philiphlop** [comment]
Solus is a Linux distro with an aim to be completely stateless (so you can replace all the system folders and there will be no lingering config files etc). The AppImage should satisfy this need with users configuration in their home folder along with notes.

**Comment by rajkrish** [comment]
Thank you for prompt response and the information.  I will try to configure Notable on Solus + Snap as described.
Thanks again.

**Comment by fabiospampinato** [comment]
I'm closing this as it seems after following the instructions provided by @PhilipWhiteside Notable can already be used in Solus Linux.

**Comment by gsbhasin123** [comment]
@fabiospampinato It can, but it would be greatly appreciated by us solus users if you could create a solus package, aka an eopkg file. https://getsol.us/articles/packaging/building-a-package/en/

I completely understand if you don't have the resources to support it though

**Comment by fabiospampinato** [comment]
I'm reopening to keep track of shipping an `eopkg` package too. 

Ideally [`electron-builder`](https://github.com/electron-userland/electron-builder) itself should add support for this, but I don't think it's going to happen anytime soon.

If anybody can provide some script for, ideally, repackaging one of the existing packages into an `eopkg` package, and that's doable from macOS, I'd be happy to add support for this 👍

**Comment by gsbhasin123** [comment]
Could you provide, say, a tar.gz file containing a binary (this will also allow inclusion into the solus official repository, and make packaging easier)? I could write a script to do it then, probably.

> If anybody can provide some script for, ideally, repackaging one of the existing packages into an eopkg package, and that's doable from macOS, I'd be happy to add support for this +1

This may be kind of hard, `eopkg` only runs on solus (but may be compilable on other linux distros). It could be in a vm though. Really, once you have a `package.yml` set up, all that needs to be edited is the checksum and the url to the tar.gz file (but this needs to be done on every update, a script to automate it could be done).

Thanks for considering the offer! :)

**Comment by gsbhasin123** [comment]
The file could look something like this:
```yaml
name       : notable
version    : a.b.c
release    : 1
source     :
    - https://notable.app/releases/a.b.c.tar.gz : SOMECHECKSUM
license    : GPL-3.0-or-later
summary    : markdown note taking app.
component  : office.notes
description: |
    The best note taking app in existence. Period. (jk)

install    : |
    sudo cp -r notable-bin /usr/local/bin
    sudo cp -r whatever.so /usr/local/share
    # and so on
```
